# Generated by Django 6.1.1 on 2026-09-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('network', '0001_initial'),
        ('subscribers', '0001_initial'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('incident_type', models.CharField(choices=[('CONNECTIVITY', 'Connectivity'), ('POWER', 'Power'), ('EQUIPMENT', 'Equipment'), ('FIBER', 'Fiber'), ('UNKNOWN', 'Unknown')], default='CONNECTIVITY', max_length=20)),
                ('status', models.CharField(choices=[('INVESTIGATING', 'Investigating'), ('ACKNOWLEDGED', 'Acknowledged'), ('MONITORING', 'Monitoring'), ('RESOLVED', 'Resolved')], default='INVESTIGATING', max_length=20)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='MAJOR', max_length=20)),
                ('affected_subscribers', models.PositiveIntegerField(default=0)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected', models.ManyToManyField(blank=True, related_name='affecting_incidents', to='subscribers.subscriber')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='common.technician')),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='network.servicearea')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='incidents.incident')),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to='network.servicearea')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to='subscribers.subscriber')),
                ('support_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='support.supportcase')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('support_case__isnull', False)), fields=('incident', 'support_case'), name='unique_incident_support_case')],
            },
        ),
    ]
