# Generated by Django 6.1.1 on 2026-09-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('DEGRADED', 'Degraded'), ('INVESTIGATING', 'Investigating'), ('OUTAGE', 'Outage')], default='OPERATIONAL', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('geometry', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('site_type', models.CharField(choices=[('POP', 'POP'), ('TOWER', 'Tower'), ('NODE', 'Node'), ('CORE', 'Core')], max_length=20)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('DEGRADED', 'Degraded'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='ONLINE', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='network.servicearea')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
