# Generated by Django 6.1.1 on 2026-09-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=32, unique=True)),
                ('category', models.CharField(choices=[('INTERNET_DOWN', 'Internet down'), ('SLOW_INTERNET', 'Slow internet'), ('ACCOUNT', 'Account'), ('BILLING', 'Billing'), ('TECHNICAL', 'Technical'), ('OTHER', 'Other')], max_length=32)),
                ('subject', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('INVESTIGATING', 'Investigating'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('VOICE', 'Voice'), ('USSD', 'USSD'), ('SMS', 'SMS'), ('DASHBOARD', 'Dashboard'), ('PHONE', 'Phone')], default='DASHBOARD', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_cases', to='network.servicearea')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_cases', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
